var hierarchy =
[
    [ "Application", null, [
      [ "Software.App", "class_software_1_1_app.html", null ],
      [ "Software.App", "class_software_1_1_app.html", null ],
      [ "Software.App", "class_software_1_1_app.html", null ]
    ] ],
    [ "BusinessLogic.Appointments", "class_business_logic_1_1_appointments.html", null ],
    [ "UserClasses.ClubsAndSocieties", "class_user_classes_1_1_clubs_and_societies.html", null ],
    [ "BusinessLogic.CreateAppointment", "class_business_logic_1_1_create_appointment.html", null ],
    [ "BusinessLogic.Encryption", "class_business_logic_1_1_encryption.html", null ],
    [ "IComponentConnector", null, [
      [ "Software.CreateStaff", "class_software_1_1_create_staff.html", null ],
      [ "Software.CreateStaff", "class_software_1_1_create_staff.html", null ],
      [ "Software.CreateUser", "class_software_1_1_create_user.html", null ],
      [ "Software.CreateUser", "class_software_1_1_create_user.html", null ],
      [ "Software.CustomerBookingDetails", "class_software_1_1_customer_booking_details.html", null ],
      [ "Software.CustomerBookingDetails", "class_software_1_1_customer_booking_details.html", null ],
      [ "Software.CustomerBookingPage", "class_software_1_1_customer_booking_page.html", null ],
      [ "Software.CustomerBookingPage", "class_software_1_1_customer_booking_page.html", null ],
      [ "Software.CustomerDashboard", "class_software_1_1_customer_dashboard.html", null ],
      [ "Software.CustomerDashboard", "class_software_1_1_customer_dashboard.html", null ],
      [ "Software.CustomerEditDetails", "class_software_1_1_customer_edit_details.html", null ],
      [ "Software.CustomerEditDetails", "class_software_1_1_customer_edit_details.html", null ],
      [ "Software.CustomerLogin", "class_software_1_1_customer_login.html", null ],
      [ "Software.CustomerLogin", "class_software_1_1_customer_login.html", null ],
      [ "Software.EmployeeBookingDetails", "class_software_1_1_employee_booking_details.html", null ],
      [ "Software.EmployeeBookingDetails", "class_software_1_1_employee_booking_details.html", null ],
      [ "Software.EmployeeBookingPage", "class_software_1_1_employee_booking_page.html", null ],
      [ "Software.EmployeeBookingPage", "class_software_1_1_employee_booking_page.html", null ],
      [ "Software.EmployeeDashboard", "class_software_1_1_employee_dashboard.html", null ],
      [ "Software.EmployeeDashboard", "class_software_1_1_employee_dashboard.html", null ],
      [ "Software.EmployeeEditDetails", "class_software_1_1_employee_edit_details.html", null ],
      [ "Software.EmployeeEditDetails", "class_software_1_1_employee_edit_details.html", null ],
      [ "Software.EmployeeLogin", "class_software_1_1_employee_login.html", null ],
      [ "Software.EmployeeLogin", "class_software_1_1_employee_login.html", null ],
      [ "Software.Home", "class_software_1_1_home.html", null ],
      [ "Software.Home", "class_software_1_1_home.html", null ],
      [ "Software.Login", "class_software_1_1_login.html", null ],
      [ "Software.MainWindow", "class_software_1_1_main_window.html", null ],
      [ "Software.MainWindow", "class_software_1_1_main_window.html", null ]
    ] ],
    [ "Software.SqlInterfacing", "class_software_1_1_sql_interfacing.html", null ],
    [ "UnitTests.Tests", "class_unit_tests_1_1_tests.html", null ],
    [ "UserClasses.User", "class_user_classes_1_1_user.html", [
      [ "UserClasses.Customer", "class_user_classes_1_1_customer.html", [
        [ "UserClasses.ExternalUser", "class_user_classes_1_1_external_user.html", null ],
        [ "UserClasses.Student", "class_user_classes_1_1_student.html", null ]
      ] ],
      [ "UserClasses.FacilitiesManagement", "class_user_classes_1_1_facilities_management.html", [
        [ "UserClasses.PersonalTrainer", "class_user_classes_1_1_personal_trainer.html", null ]
      ] ]
    ] ],
    [ "BusinessLogic.UserMessage", "class_business_logic_1_1_user_message.html", null ],
    [ "BusinessLogic.Util", "class_business_logic_1_1_util.html", null ],
    [ "BusinessLogic.Validator", "class_business_logic_1_1_validator.html", [
      [ "BusinessLogic.CheckEmailFormat", "class_business_logic_1_1_check_email_format.html", null ],
      [ "BusinessLogic.CheckForSpecialCharacters", "class_business_logic_1_1_check_for_special_characters.html", null ],
      [ "BusinessLogic.CheckIsAllDigits", "class_business_logic_1_1_check_is_all_digits.html", null ],
      [ "BusinessLogic.CheckIsAllLetters", "class_business_logic_1_1_check_is_all_letters.html", null ],
      [ "BusinessLogic.CheckIsNotNull", "class_business_logic_1_1_check_is_not_null.html", null ],
      [ "BusinessLogic.CheckIsNotWhiteSpace", "class_business_logic_1_1_check_is_not_white_space.html", null ],
      [ "BusinessLogic.CheckNumberOfCharacters", "class_business_logic_1_1_check_number_of_characters.html", null ]
    ] ],
    [ "UserClasses.Volunteer", "class_user_classes_1_1_volunteer.html", null ],
    [ "Window", null, [
      [ "Software.CreateStaff", "class_software_1_1_create_staff.html", null ],
      [ "Software.CreateStaff", "class_software_1_1_create_staff.html", null ],
      [ "Software.CreateStaff", "class_software_1_1_create_staff.html", null ],
      [ "Software.CreateUser", "class_software_1_1_create_user.html", null ],
      [ "Software.CreateUser", "class_software_1_1_create_user.html", null ],
      [ "Software.CreateUser", "class_software_1_1_create_user.html", null ],
      [ "Software.CustomerBookingDetails", "class_software_1_1_customer_booking_details.html", null ],
      [ "Software.CustomerBookingDetails", "class_software_1_1_customer_booking_details.html", null ],
      [ "Software.CustomerBookingDetails", "class_software_1_1_customer_booking_details.html", null ],
      [ "Software.CustomerBookingPage", "class_software_1_1_customer_booking_page.html", null ],
      [ "Software.CustomerBookingPage", "class_software_1_1_customer_booking_page.html", null ],
      [ "Software.CustomerBookingPage", "class_software_1_1_customer_booking_page.html", null ],
      [ "Software.CustomerDashboard", "class_software_1_1_customer_dashboard.html", null ],
      [ "Software.CustomerDashboard", "class_software_1_1_customer_dashboard.html", null ],
      [ "Software.CustomerDashboard", "class_software_1_1_customer_dashboard.html", null ],
      [ "Software.CustomerEditDetails", "class_software_1_1_customer_edit_details.html", null ],
      [ "Software.CustomerEditDetails", "class_software_1_1_customer_edit_details.html", null ],
      [ "Software.CustomerEditDetails", "class_software_1_1_customer_edit_details.html", null ],
      [ "Software.CustomerLogin", "class_software_1_1_customer_login.html", null ],
      [ "Software.CustomerLogin", "class_software_1_1_customer_login.html", null ],
      [ "Software.CustomerLogin", "class_software_1_1_customer_login.html", null ],
      [ "Software.EmployeeBookingDetails", "class_software_1_1_employee_booking_details.html", null ],
      [ "Software.EmployeeBookingDetails", "class_software_1_1_employee_booking_details.html", null ],
      [ "Software.EmployeeBookingDetails", "class_software_1_1_employee_booking_details.html", null ],
      [ "Software.EmployeeBookingPage", "class_software_1_1_employee_booking_page.html", null ],
      [ "Software.EmployeeBookingPage", "class_software_1_1_employee_booking_page.html", null ],
      [ "Software.EmployeeBookingPage", "class_software_1_1_employee_booking_page.html", null ],
      [ "Software.EmployeeDashboard", "class_software_1_1_employee_dashboard.html", null ],
      [ "Software.EmployeeDashboard", "class_software_1_1_employee_dashboard.html", null ],
      [ "Software.EmployeeDashboard", "class_software_1_1_employee_dashboard.html", null ],
      [ "Software.EmployeeEditDetails", "class_software_1_1_employee_edit_details.html", null ],
      [ "Software.EmployeeEditDetails", "class_software_1_1_employee_edit_details.html", null ],
      [ "Software.EmployeeEditDetails", "class_software_1_1_employee_edit_details.html", null ],
      [ "Software.EmployeeLogin", "class_software_1_1_employee_login.html", null ],
      [ "Software.EmployeeLogin", "class_software_1_1_employee_login.html", null ],
      [ "Software.EmployeeLogin", "class_software_1_1_employee_login.html", null ],
      [ "Software.Home", "class_software_1_1_home.html", null ],
      [ "Software.Home", "class_software_1_1_home.html", null ],
      [ "Software.Home", "class_software_1_1_home.html", null ],
      [ "Software.Login", "class_software_1_1_login.html", null ],
      [ "Software.MainWindow", "class_software_1_1_main_window.html", null ],
      [ "Software.MainWindow", "class_software_1_1_main_window.html", null ],
      [ "Software.MainWindow", "class_software_1_1_main_window.html", null ]
    ] ]
];